# Generated by Django 4.2.4 on 2023-09-05 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('for_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSH', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('md', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.modelwork', to_field='nameMW', verbose_name='Модель работы')),
                ('moe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.methodofexport', to_field='nameME', verbose_name='Метод отгрузки')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.marketplace', to_field='nameMP', verbose_name='Маркетплейс')),
                ('tt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.tarifftranslate', to_field='nameTT', verbose_name='Тариф перевода денег')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_shop', models.CharField(max_length=20, verbose_name='Номер')),
                ('sku_p', models.CharField(max_length=20, verbose_name='Уникальный номер на площадке')),
                ('name_p', models.CharField(max_length=20, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(null=True, verbose_name='Цена продажи')),
                ('profit', models.FloatField(null=True, verbose_name='Прибыль')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_users.shop', to_field='nameSH', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, verbose_name='Уникальный номер на площадке')),
                ('nameP', models.CharField(max_length=20, verbose_name='Название')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('article', models.CharField(max_length=20, verbose_name='Артикул')),
                ('price', models.FloatField(default=0, null=True, verbose_name='Цена продажи')),
                ('profit', models.FloatField(default=0, null=True, verbose_name='Прибыль')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_users.shop', to_field='nameSH', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
