# Generated by Django 4.2.4 on 2023-09-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_users', '0002_product_d_product_gabarits_product_sh_product_v_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='d',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gabarits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sh',
        ),
        migrations.RemoveField(
            model_name='product',
            name='v',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weigh',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='d',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='gabarits',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sh',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='v',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='weigh',
        ),
    ]
