# Generated by Django 4.2.4 on 2023-09-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=60, verbose_name='Имя категории')),
                ('cost_fbo', models.FloatField(verbose_name='Комиссия для модели FBO')),
                ('cost_fbs', models.FloatField(verbose_name='Комиссия для модели FBS')),
            ],
            options={
                'verbose_name': 'Категория Озон',
                'verbose_name_plural': 'Категории Озон',
            },
        ),
        migrations.CreateModel(
            name='CategorySBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=60, verbose_name='Имя категории')),
                ('cost_fbo', models.FloatField(verbose_name='Комиссия для модели FBO')),
                ('cost_fbs', models.FloatField(verbose_name='Комиссия для модели FBS')),
            ],
            options={
                'verbose_name': 'Категория СберМегаМаркет',
                'verbose_name_plural': 'Категории СберМегаМаркет',
            },
        ),
        migrations.CreateModel(
            name='CategoryYM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_parents', models.CharField(max_length=10, verbose_name='Родительская')),
                ('name_dote', models.CharField(max_length=50, verbose_name='Дочерняя')),
                ('name_full', models.CharField(max_length=60, verbose_name='Полное имя категории')),
                ('cost_fby', models.FloatField(verbose_name='Комиссия для модели FBY')),
                ('cost_fbs', models.FloatField(null=True, verbose_name='Комиссия для модели FSY')),
            ],
            options={
                'verbose_name': 'Категория Яндекс.Маркет',
                'verbose_name_plural': 'Категории Яндекс.Маркет',
            },
        ),
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMP', models.CharField(max_length=20, unique=True, verbose_name='Название МП')),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
            },
        ),
        migrations.CreateModel(
            name='TariffTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTT', models.CharField(max_length=20, unique=True, verbose_name='Частота выплат')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.marketplace', to_field='nameMP', verbose_name='Доступно для МП')),
            ],
            options={
                'verbose_name': 'Тариф перевода денег',
                'verbose_name_plural': 'Тарифы перевода денег',
            },
        ),
        migrations.CreateModel(
            name='ModelWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMW', models.CharField(max_length=10, unique=True, verbose_name='Название модели')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.marketplace', to_field='nameMP', verbose_name='Доступе для МП')),
            ],
            options={
                'verbose_name': 'Модель продаж',
                'verbose_name_plural': 'Модели продаж',
            },
        ),
        migrations.CreateModel(
            name='MethodofExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameME', models.CharField(max_length=20, unique=True, verbose_name='Метод отгрузки')),
                ('cost', models.FloatField(verbose_name='Стоимость отгрузки')),
                ('mp', models.ForeignKey(default='МП', on_delete=django.db.models.deletion.CASCADE, to='for_admin.marketplace', to_field='nameMP', verbose_name='Доступно для МП')),
                ('mw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.modelwork', to_field='nameMW', verbose_name='Доступно для модели')),
            ],
            options={
                'verbose_name': 'Метод отгрузки',
                'verbose_name_plural': 'Методы для отгрузки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCT', models.CharField(max_length=20, unique=True, verbose_name='Имя')),
                ('cost', models.FloatField(verbose_name='Комиссия')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.marketplace', to_field='nameMP', verbose_name='Доступно для МП')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
