# Generated by Django 4.2.4 on 2023-09-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifftranslate',
            name='cost_tt_client',
            field=models.FloatField(default=0.12, verbose_name='Стоимость за прием платежей покупателей'),
        ),
    ]
