# Generated by Django 4.2.4 on 2023-09-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('for_admin', '0002_tarifftranslate_cost_tt_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnouthTariffYM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тариф за')),
                ('condition', models.CharField(max_length=50, verbose_name='Условие')),
                ('w', models.FloatField(verbose_name=' Вес товара')),
                ('sums', models.FloatField(verbose_name='Сумма сторон')),
                ('procent', models.FloatField(verbose_name='Процент комиссии')),
                ('min', models.FloatField(verbose_name='Не меньше')),
                ('max', models.FloatField(verbose_name='Не больше')),
                ('cost_else', models.FloatField(verbose_name='Стоимость при невыполнении условия')),
                ('mw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.modelwork', to_field='nameMW', verbose_name='Доступно для модели')),
            ],
            options={
                'verbose_name': 'Тариф Яндекс.Маркет',
                'verbose_name_plural': 'Другие тарифы Яндекс.Маркет',
            },
        ),
    ]
